GET http://localhost:8080/api/users/100000

> {%
    client.test("Status should be 401", function() {
        client.assert(response.status === 401);
    });
%}

###
GET http://localhost:8080/api/users/3
X-I-AM: YGDWSI

> {%
    client.test("Status should be 200", function() {
        client.assert(response.status === 200);

        client.assert(response.body.id === '3');
        client.assert(response.body.name === 'carol');
        client.assert(response.body.age === 10);
    });
%}

###
POST http://localhost:8080/api/users/signup
Content-Type: application/json

{
  "name": "carol",
  "age": 10,
  "gender": "F",
  "password": "1234",
  "profileImage": "3"
}
